name: test-harness-afgo-afgo
# RUNSET_NAME: "AF-Go to AF-Go"
# Scope: pre-AIP 2.0
# Exceptions: None
# 
# Summary
#
# This runset uses the current main branch of Aries Framework Go for all of the agents. The runset runs some of the tests in the suite
# that are expected to pass given the current state of Aries Framework Go support for 2 DID exchange.
#
# Current
# 
# The tests that use an implicit invitation are not currently working. The issue is being investigated -- this feature may not be
# supported in Aries Framework Go.
# 
# *Status Note Updated: 2021.03.05*
#
# End
on:
  workflow_dispatch:
  schedule:
    - cron: "45 0 * * *"
defaults:
  run:
    shell: bash
jobs:
  test:
    runs-on: ubuntu-latest
    if: (github.event_name == 'schedule' && github.repository == 'hyperledger/aries-agent-test-harness') || (github.event_name != 'schedule')
    steps:
      - name: checkout-test-harness
        uses: actions/checkout@v2
        with:
          path: test-harness
      - name: run-von-network
        uses: ./test-harness/actions/run-von-network
      - name: run-indy-tails-server
        uses: ./test-harness/actions/run-indy-tails-server
      - name: run-test-harness-wo-reports
        uses: ./test-harness/actions/run-test-harness-wo-reports
        with:
          BUILD_AGENTS: "-a afgo-master"
          TEST_AGENTS: "-d afgo-master"
          TEST_SCOPE: "-t @RFC0023 -t ~@wip"
          REPORT_PROJECT: afgo 
        continue-on-error: true
      - name: run-send-gen-test-results-secure
        uses: ./test-harness/actions/run-send-gen-test-results-secure
        with:
          REPORT_PROJECT: afgo 
          ADMIN_USER: ${{ secrets.AllureAdminUser }}
          ADMIN_PW: ${{ secrets.AllureAdminPW }}
